spring.application.name=BankingApp
spring.datasource.url=jdbc:mysql://localhost:8080/database
spring.jpa.hibernate.ddl-auto=update
server.port=8082

finance.alpha.vantage.api.key=
finance.use.mock.data=true

# Session configuration
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
